// resources/js/components/Dialog.vue
<template>
    <div class="dialog" :class="{hide: !notices.message}" @click="close()">
        <div class="dialog-content" :class="{hide: !notices.message}">
            <div class="dialog-content-header">
                <div class="dialog-content-title" v-text="notices.title"></div>
            </div>
            <div class="dialog-content-body" v-html="notices.message" :class="{'field-validation-error': notices.error}"></div>
            <div class="dialog-content-footer">
                <button type="button" @click="close()">閉じる</button>
            </div>
        </div>
    </div>
</template>

<script>
    export default {
        data: () => {
            return {
            }
        },
        props: ['notices'],
        methods: {
            close() {
                this.$emit('close');
            },
        },
    }
</script>

// resources/ts/components/parts/dialog.component.ts
import { Component } from '@angular/core';
import { DialogService } from '../../services/dialog.service';

declare var require: any;

/**
 * ダイアログを表示するためのコンポーネント
 */
@Component({
    selector: '[dialog]',
    template: require('./dialog.component.html'),
})
export class Dialog {
    constructor(private dialog: DialogService) { }
}

<div class="dialog" [class.hide]="!isShow()">
    <div class="dialog-content">
        <div class="dialog-content-header" *ngIf="dialog.title">
            <div class="dialog-content-title" [innerText]="dialog.title"></div>
        </div>
        <div class="dialog-content-body">
            <ul class="dialog-content-body-text" [class.field-validation-error]="dialog.error">
                <li *ngFor="let message of dialog.messages" [innerText]="message"></li>
            </ul>
        </div>
        <div class="dialog-content-footer">
            <button (click)="dialog.close()">閉じる</button>
        </div>
    </div>
</div>
