// resources/js/components/Instruction.vue
<template>
    <div class="menu-cooking">
        <div class="center">
            <button type="button" class="btn-add" @click="addRow()">追加</button>
            <button type="button" class="btn-delete" @click="deleteRow()">削除</button>
        </div>
        <ul class="cookings">
            <li v-for="instruction in instructions">
                <span class="cooking-order" v-text="getOrder(instruction)"></span>：
                <input type="text" name="instructions.description" v-model="instruction.description" class="cooking-description">
            </li>
        </ul>
    </div>
</template>

<script>
    export default {
        data: () => {
            return {
            }
        },
        props: ['instructions'],
        methods: {
            addRow() {
                this.instructions.push({});
            },
            deleteRow() {
                this.instructions.pop();
            },
            getOrder(_instruction) {
                if (!_instruction.sort_order) {
                    _instruction.sort_order = this.instructions.length;
                }
                return _instruction.sort_order;
            },
        },
    };
</script>

// resources/scripts/components/cuisine-detail/instruction.component.ts
import { Component, Input } from '@angular/core';

declare var require: any;

/**
 * 調理手順コンポーネント
 */
@Component({
  selector: '[instructions]',
  template: require('./instruction.component.html'),
})
export class InstructionComponent {
  @Input() public items: any[];

  public addRow() {
    this.items.push({});
  }

  public deleteRow() {
    this.items.pop();
  }

  public getOrder(_item: any) {
    if (!_item.sort_order) {
      _item.sort_order = this.items.length;
    }
    return `${_item.sort_order}：`;
  }
}

<div class="category-header">
    <div class="category-name">【調理手順】</div>
    <div class="button-wrap">
        <button type="button" class="btn-little btn-add" (click)="addRow()">
            <i class="fa fa-plus" area-hidden="true"></i>
        </button>
        <button type="button" class="btn-little btn-delete" (click)="deleteRow()">
            <i class="fa fa-minus" area-hidden="true"></i>
        </button>
    </div>
</div>
<ul class="instructions list-box">
    <li class="list-box-header">
        <span class="cooking-order">No.</span>
        <span>手順</span>
    </li>
    <li class="list-box-item" *ngFor="let item of items">
        <span class="cooking-order" [innerText]="getOrder(item)"></span>
        <textarea name="item.description" [(ngModel)]="item.description" class="cooking-description"></textarea>
    </li>
</ul>
