// resources/ts/components/cuisine-detail/detail.component.ts
import { Component, OnInit } from '@angular/core';
import { Http } from '@angular/http';
import { ActivatedRoute, Router } from '@angular/router';
import { DialogService } from '../../services/dialog.service';

declare var require: any;

/**
 * レシピ詳細コンポーネント
 */
@Component({
    selector: '.content-inner',
    template: require('./detail.component.html'),
})
export class DetailComponent implements OnInit {
    items = new Array();
    params = new Object();
    cuisineId = 1;
    cuisine = {
        instructions: new Array(),
        foodstuffs: new Array(),
    };
    types = this.getTypes();
    dataList: string[];

    constructor(private http: Http, private router: Router, private route: ActivatedRoute, private dialog: DialogService) { }

    toSearch() {
        this.router.navigate(['/']);
    }

    getLabel() {
        return (this.cuisineId ? '更新' : '登録');
    }

    /**
     * 保存処理
     */
    save() {
        if (this.cuisineId) {
            this.http.put(this.getUrl('put'), this.cuisine)
                .subscribe((res) => {
                    this.cuisine = res.json();
                    this.dialog.open('メッセージ', 'レシピを更新しました。');
                }, (err) => this.apiError(err));
        } else {
            this.http.post(this.getUrl('post'), this.cuisine)
                .subscribe((res) => {
                    this.cuisine = res.json();
                    this.dialog.open('メッセージ', 'レシピを登録しました。');
                }, (err) => this.apiError(err));
        }
    }

    /**
     * レスポンスからエラーメッセージを生成
     *
     * @param err
     */
    apiError(err: Response) {
        if (err.status !== 400) {
            this.dialog.open('エラー', 'エラーが発生しました。', true);
            return;
        }
        const errors = new Array();
        const obj = err.json();
        Object.keys(obj).forEach((k) => {
            const values: any[] = obj[k] || [];
            values.forEach((v) => {
                if (v instanceof Object) {
                    Object.keys(v).forEach((ck) => {
                        errors.push(`${ck}: ${v[ck]}`);
                    });
                } else {
                    errors.push(`${k}: ${v}`);
                }
            });
        });
        this.dialog.open('エラー', errors.join('<br>'), true);
    }

    /**
     * {@inheritDoc}
     */
    ngOnInit() {
        // パラメータからIDを取得
        this.route.params.subscribe((params) => {
            this.cuisineId = params['id'];

            if (!this.cuisineId) {
                for (let i = 0; i < 3; i++) {
                    this.cuisine.instructions.push({
                        sort_order: i + 1,
                    });
                    this.cuisine.foodstuffs.push({});
                }
            } else {
                this.http.get(this.getUrl('get')).forEach((res) => {
                    this.cuisine = res.json();
                });
            }

            // 食材の補完情報を取得
            this.http.get('/api/foodstuffs/').forEach((res) => {
                this.dataList = res.json();
            });
        });
    }

    /**
     * 対象APIのURLを取得
     *
     * @private
     * @param _type
     */
    private getUrl(_type: string) {
        switch (_type.toUpperCase()) {
            case 'GET':
            case 'PUT':
            case 'DELETE':
                return `/api/cuisine/${this.cuisineId}/`;
            case 'POST':
                return '/api/cuisine/';
        }
        return '';
    }

    /**
     * 分類一覧取得
     *
     * @private
     * @return {Array} 分類一覧
     */
    private getTypes() {
        return [
            '', '主菜', '副菜', '主食', 'デザート', 'その他',
        ];
    }
}

<div class="menu-detail">
    <div class="recipe-row-box">
        <div class="label-column">
            <label>名前</label>
        </div>
        <div class="input-column">
            <input type="text" class="name" name="name" [(ngModel)]="cuisine.name">
        </div>
    </div>
    <div class="recipe-row-box">
        <div class="label-column">
            <label>分類</label>
        </div>
        <div class="input-column">
            <select name="classification" [(ngModel)]="cuisine.classification">
                <option *ngFor="let type of types" [value]="type" [innerText]="type"></option>
            </select>
        </div>
    </div>
    <div class="recipe-row-box">
        <div class="label-column">
            <label>カロリー</label>
        </div>
        <div class="input-column">
            <input type="number" [(ngModel)]="cuisine.ingestion_kcal">
            <span class="after-label">KCal</span>
        </div>
    </div>
    <div class="recipe-row-box">
        <div class="label-column">
            <label>分量</label>
        </div>
        <div class="input-column">
            <input type="number" [(ngModel)]="cuisine.serves">
            <span class="after-label">人前</span>
        </div>
    </div>
    <div class="recipe-row-box button-wrap">
        <button type="button" (click)="toSearch()">検索画面へ</button>
        <button type="button" (click)="save()" class="btn btn-save" [innerText]="getLabel()"></button>
    </div>
</div>
<div class="menu-detail-other">
    <div class="menu-items" instructions [items]="cuisine.instructions"></div>
    <div class="menu-items" foodstuffs [items]="cuisine.foodstuffs"></div>
</div>
<datalist id="foodstuffs">
    <option *ngFor="let item of dataList" [value]="item.name"></option>
</datalist>

// resources/js/components/cuisine/Detail.vue
<template>
    <div class="content-inner">
        <div class="menu-detail">
            <label>名前：</label>
            <input type="text" name="name" v-model="cuisine.name">
            <label>種類：</label>
            <select name="classification" v-model="cuisine.classification">
                <option v-for="(list, idx) in types" :key="idx" :value="list" v-text="list"></option>
            </select>
            <label>Kcal：</label>
            <input type="number" v-model="cuisine.ingestion_kcal">
            <label>種類：</label>
            <input type="number" v-model="cuisine.create_number_of_times">
            <div class="button-wrap">
                <button type="button" @click="save()" class="btn btn-default" v-text="getLabel()"></button>
                <button type="button" class="btn btn-default">メール送信</button>
            </div>
        </div>
        <div class="menu-detail-other">
            <instructions :items="cuisine.instructions"></instructions>
            <foodstuffs :items="cuisine.foodstuffs"></foodstuffs>
        </div>
        <div class="footer-button">
            <button type="button" @click="toSearch('cuisine')">検索画面へ</button>
        </div>
        <datalist id="foodstuffs">
            <option v-for="(item, idx) in dataList" :key="idx" :value="item.name"></option>
        </datalist>
    </div>
</template>

<script>
    import Instruction from './Instruction.vue';
    import Foodstuff from './Foodstuff.vue';

    export default {
        props: {
            cuisineId: Number,
            user: String,
        },
        data: () => {
            return {
                cuisine: {
                    instructions: [],
                    foodstuffs: [],
                },
                types: [
                    '主菜', '副菜', '主食', 'デザート', 'その他',
                ],
                dataList: [],
                selectId: 0,
            }
        },
        components: {
            instructions: Instruction,
            foodstuffs: Foodstuff,
        },
        methods: {
            toSearch() {
                location.href = '/recipe/cuisine';
            },
            getLabel() {
                return (this.selectId ? '更新' : '登録');
            },
            getUrl(_type) {
                _type = _type.toUpperCase();
                switch (_type) {
                    case 'GET':
                    case 'PUT':
                    case 'DELETE':
                        return `/recipe/api/cuisine/${this.selectId}/`;
                    case 'POST':
                        return `/recipe/api/cuisine/`;
                }
                return '';
            },
            save() {
                if (this.selectId) {
                    this.$http.put(this.getUrl('put'), JSON.stringify(this.cuisine), {
                        headers: {
                            'X-Access-User': this.user,
                        },
                    }).then((data) => {
                        this.cuisine = data.body;
                        this.$emit('dialog', {
                            title: 'メッセージ',
                            message: 'レシピを更新しました。',
                        });
                    }).catch(this.apiError);
                } else {
                    this.$http.post(this.getUrl('post'), JSON.stringify(this.cuisine), {
                        headers: {
                            'X-Access-User': this.user,
                        },
                    }).then((data) => {
                        this.cuisine = data.body;
                        this.selectId = this.cuisine.id;
                        this.$emit('dialog', {
                            title: 'メッセージ',
                            message: 'レシピを登録しました。',
                        });
                    }).catch(this.apiError);
                }
            },
            apiError(res) {
                console.log(res);
                // エラーメッセージを生成
                const errors = [];
                const errorObj = JSON.parse(res.bodyText);
                Object.keys(errorObj).forEach(k => {
                    errorObj[k].forEach(v => {
                        if (v instanceof Object) {
                            Object.keys(v).forEach(ck => {
                                errors.push(`${ck}: ${v[ck]}`);
                            });
                        } else {
                            errors.push(`${k}: ${v}`);
                        }
                    });
                })
                this.$emit('dialog', {
                    error: true,
                    title: 'エラー',
                    message: errors.join('<br>'),
                });
            },
        },
        created() {
            // レシピを取得
            if (this.cuisineId) {
                this.selectId = this.cuisineId;
                this.$http.get(this.getUrl('get')).then((data) => {
                    this.cuisine = data.body;
                });
            }
            // 食材の補完情報を取得
            this.$http.get('/recipe/api/foodstuffs/').then((data) => {
                this.dataList = data.body;
            });
        },
        mounted() {
            if (!this.selectId) {
                for (let i = 0; i < 3; i++) {
                    this.cuisine.instructions.push({
                        sort_order: i + 1,
                    });
                    this.cuisine.foodstuffs.push({});
                }
            }
        }
    };
</script>
