// resources/scripts/components/cuisine-detail/foodstuff.component.ts
import { Component, Input } from '@angular/core';

declare var require: any;

/**
 * 食材コンポーネント
 */
@Component({
  selector: '[foodstuffs]',
  template: require('./foodstuff.component.html'),
})
export class FoodstuffComponent {
  @Input() public items: any[];

  public addRow() {
    this.items.push({});
  }

  public deleteRow() {
    this.items.pop();
  }
}

<div class="category-header">
    <div class="category-name">【食材】</div>
    <div class="button-wrap">
        <button type="button" class="btn-little btn-add" (click)="addRow()">
            <i class="fa fa-plus" area-hidden="true"></i>
        </button>
        <button type="button" class="btn-little btn-delete" (click)="deleteRow()">
            <i class="fa fa-minus" area-hidden="true"></i>
        </button>
    </div>
</div>
<ul class="foodstuffs list-box">
    <li class="list-box-header">
        <span class="foodstuff-name">食材名</span>
        <span class="foodstuff-quantity">個数</span>
    </li>
    <li class="list-box-item" *ngFor="let item of items">
        <input type="text" class="foodstuff-name" [(ngModel)]="item.name" list="foodstuffs">
        <input type="text" class="foodstuff-quantity" [(ngModel)]="item.quantity">
    </li>
</ul>

// resources/js/components/cuisine/Foodstuff.vue
<template>
    <div class="menu-items">
        <div class="center">
            <button type="button" class="btn-add" @click="addRow()">追加</button>
            <button type="button" class="btn-delete" @click="deleteRow()">削除</button>
        </div>
        <ul class="foodstuffs">
            <li v-for="(item, idx) in items" :key="idx">
                <input type="text" v-model="item.name" list="foodstuffs">
                <input type="text" v-model="item.quantity">
            </li>
        </ul>
    </div>
</template>

<script>
    export default {
        data: () => {
            return {
            };
        },
        props: ['items'],
        methods: {
            addRow() {
                this.items.push({});
            },
            deleteRow() {
                this.items.pop();
            },
        },
    };
</script>
