// resources/ts/components/cuisine-detail/foodstuff.component.ts
import { Component, Input } from '@angular/core';
import { NgIf, NgFor, NgClass } from '@angular/common';
import { NgModel } from '@angular/forms';

declare var require: any;

/**
 * 食材コンポーネント
 */
@Component({
    selector: '[foodstuffs]',
    template: require('./foodstuff.component.html'),
})
export class FoodstuffComponent {
    @Input() items: any[];

    addRow() {
        this.items.push({});
    }

    deleteRow() {
        this.items.pop();
    }
}

<div class="center">
    <button type="button" class="btn-add" (click)="addRow()">追加</button>
    <button type="button" class="btn-delete" (click)="deleteRow()">削除</button>
</div>
<ul class="foodstuffs">
    <li *ngFor="let item of items">
        <input type="text" [(ngModel)]="item.name" list="foodstuffs">
        <input type="text" [(ngModel)]="item.quantity">
    </li>
</ul>

// resources/js/components/cuisine/Foodstuff.vue
<template>
    <div class="menu-items">
        <div class="center">
            <button type="button" class="btn-add" @click="addRow()">追加</button>
            <button type="button" class="btn-delete" @click="deleteRow()">削除</button>
        </div>
        <ul class="foodstuffs">
            <li v-for="(item, idx) in items" :key="idx">
                <input type="text" v-model="item.name" list="foodstuffs">
                <input type="text" v-model="item.quantity">
            </li>
        </ul>
    </div>
</template>

<script>
    export default {
        data: () => {
            return {
            };
        },
        props: ['items'],
        methods: {
            addRow() {
                this.items.push({});
            },
            deleteRow() {
                this.items.pop();
            },
        },
    };
</script>
