// resources/ts/components/cuisine-detail/instruction.component.ts
import { Component, Input, Output, EventEmitter, OnInit } from '@angular/core';
import { Http, Headers, RequestOptions, URLSearchParams } from '@angular/http';
import { NgIf, NgFor, NgClass } from '@angular/common';
import { NgModel } from '@angular/forms';

declare var require: any;

/**
 * 調理手順コンポーネント
 */
@Component({
    selector: '[instructions]',
    template: require('./instruction.component.html'),
})
export class InstructionComponent {
    @Input() items: any[];

    addRow() {
        this.items.push({});
    }

    deleteRow() {
        this.items.pop();
    }

    getOrder(_item: any) {
        if (!_item.sort_order) {
            _item.sort_order = this.items.length;
        }
        return _item.sort_order;
    }
}

<div class="center">
    <button type="button" class="btn-add" (click)="addRow()">追加</button>
    <button type="button" class="btn-delete" (click)="deleteRow()">削除</button>
</div>
<ul class="instructions">
    <li *ngFor="let item of items">
        <span class="cooking-order" [innerText]="getOrder(item)"></span>：
        <input type="text" name="item.description" [(ngModel)]="item.description" class="cooking-description">
    </li>
</ul>

// resources/js/components/cuisine/Instruction.vue
<template>
    <div class="menu-cooking">
        <div class="center">
            <button type="button" class="btn-add" @click="addRow()">追加</button>
            <button type="button" class="btn-delete" @click="deleteRow()">削除</button>
        </div>
        <ul class="cookings">
            <li v-for="instruction in instructions">
                <span class="cooking-order" v-text="getOrder(instruction)"></span>：
                <input type="text" name="instructions.description" v-model="instruction.description" class="cooking-description">
            </li>
        </ul>
    </div>
</template>

<script>
    export default {
        data: () => {
            return {
            }
        },
        props: ['instructions'],
        methods: {
            addRow() {
                console.log(this.instructions);
                this.instructions.push({});
            },
            deleteRow() {
                this.instructions.pop();
            },
            getOrder(_instruction) {
                if (!_instruction.sort_order) {
                    _instruction.sort_order = this.instructions.length;
                }
                return _instruction.sort_order;
            },
        },
    };
</script>
